import Head from "next/head";
import Product from "../components/Product";
import React, { useState } from "react";
import NavBar from "../components/Nav";
import { useRecoilState } from "recoil";
import { post } from "../components/Product";

export default function Home() {
  const [postage, setPostage] = useRecoilState(post);
  const [code, setCode] = useState("");
  const [product, setProduct] = useState([]);
  const [loading, setLoading] = useState(false);
  const [supplier, setSupplier] = useState("");

  const loadProduct = async () => {
    setPostage("");
    setProduct([]);
    setLoading(true);
    let req;
    if (supplier === "Creative") {
      req = await fetch(`/api/cid/${code}`);
    } else {
      req = await fetch(`/api/id/${code}`);
    }
    const json = await req.json();
    setProduct(json);
    setLoading(false);
    console.log(product);
  };

  const handleKeyPress = (event) => {
    if (event.key === "Enter") {
      loadProduct();
    }
  };
  return (
    <>
      <NavBar />
      <div>
        <Head>
          <title>MH Web Tool</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>
        <div className="buttons">
          <select
            value={supplier}
            onChange={(e) => setSupplier(e.target.value)}
          >
            <option value="Hannants">Hannants</option>
            <option value="Creative">Creative</option>
          </select>
          <input
            value={code}
            id="code"
            placeholder="Enter a Product Code"
            onDoubleClick={(e) => (e.target.value = "")}
            onChange={(e) => setCode(e.target.value)}
            onKeyPress={handleKeyPress}
          />
          <button onClick={() => loadProduct()} id="pbtn">
            Load
          </button>
          {loading && <div>LOADING</div>}
        </div>
        <Product productData={product} />
      </div>
    </>
  );
}
