import Head from "next/head";
import Prices from "../components/Price-info";
import React, { useState } from "react";
import NavBar from "../components/Nav";

export default function PriceInfo() {
  return (
    <>
      <NavBar />
      <div>
        <Head>
          <title>MH Web Tool</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>
        <p>
          <Prices />
        </p>
      </div>
    </>
  );
}
